<?php
require_once __DIR__ . '/auth/auth_check.php';
require_once __DIR__ . '/config/billing_helpers.php';
$pageTitle = 'Clients'; $active = 'clients';
$clients = fetch_clients(); $services = fetch_active_services();
include __DIR__ . '/includes/head.php'; include __DIR__ . '/includes/sidebar.php'; include __DIR__ . '/includes/topbar.php';
?>
<div class="page-title"><div><h1>Clients</h1><p class="muted">Client records and assigned services.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#clientModal" onclick="clientForm.reset();client_id.value=''"><i class="bi bi-plus-lg me-2"></i>Add Client</button></div>
<div class="panel-card"><table class="table table-striped data-table nowrap w-100"><thead><tr><th>Name</th><th>Trade</th><th>Mobile</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php foreach ($clients as $c): ?><tr><td><?= e($c['name']) ?></td><td><?= e($c['trade_name']) ?></td><td><?= e($c['mobile']) ?></td><td><?= e($c['email']) ?></td><td><span class="badge text-bg-<?= $c['status'] ? 'success' : 'secondary' ?>"><?= $c['status'] ? 'Active' : 'Inactive' ?></span></td><td><form class="d-inline" action="client-view.php" method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="client_token" value="<?= e(encode_token($c['id'])) ?>"><button class="btn btn-sm btn-outline-info"><i class="bi bi-eye"></i></button></form> <button class="btn btn-sm btn-outline-primary edit-client" data-row='<?= e(json_encode($c)) ?>'><i class="bi bi-pencil"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div>
<div class="modal fade" id="clientModal" tabindex="-1"><div class="modal-dialog modal-xl"><form class="modal-content ajax-reload" id="clientForm" action="ajax/client-save.php" method="post"><div class="modal-header"><h5 class="modal-title">Client</h5><button class="btn-close" data-bs-dismiss="modal" type="button"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" id="client_id"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Trade Name</label><input class="form-control" name="trade_name"></div><div class="col-md-4"><label class="form-label">Mobile</label><input class="form-control" name="mobile"></div><div class="col-md-4"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp_number"></div><div class="col-md-4"><label class="form-label">Email</label><input class="form-control" name="email" type="email"></div><div class="col-md-2"><label class="form-label">PAN</label><input class="form-control" name="pan"></div><div class="col-md-2"><label class="form-label">GSTIN</label><input class="form-control" name="gstin"></div><div class="col-md-5"><label class="form-label">Address</label><input class="form-control" name="address"></div><div class="col-md-2"><label class="form-label">City</label><input class="form-control" name="city"></div><div class="col-md-2"><label class="form-label">State</label><input class="form-control" name="state"></div><div class="col-md-1"><label class="form-label">PIN</label><input class="form-control" name="pincode"></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1">Active</option><option value="0">Inactive</option></select></div></div><hr><h6>Assigned Services</h6><div class="row g-2" id="serviceChecks"><?php foreach ($services as $s): ?><div class="col-md-4"><label class="form-check border rounded p-2"><input class="form-check-input service-check" type="checkbox" name="services[]" value="<?= (int)$s['id'] ?>" data-fee="<?= e($s['default_fee']) ?>"> <?= e($s['service_name']) ?><input class="form-control form-control-sm mt-2" type="number" step="0.01" name="assigned_fee[<?= (int)$s['id'] ?>]" value="<?= e($s['default_fee']) ?>"></label></div><?php endforeach; ?></div></div><div class="modal-footer"><button class="btn btn-primary" type="submit">Save Client</button></div></form></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{bindAjaxForm('.ajax-reload');document.querySelectorAll('.edit-client').forEach(b=>b.onclick=async()=>{const d=JSON.parse(b.dataset.row);clientForm.reset();client_id.value=d.id;for(const k in d){const el=clientForm.elements[k];if(el)el.value=d[k]??'';}const fd=new FormData();fd.append('client_id',d.id);const data=await safeFetch('ajax/get-client-services.php',{method:'POST',body:fd});document.querySelectorAll('.service-check').forEach(c=>c.checked=false);if(data.success){data.services.forEach(s=>{const c=document.querySelector('.service-check[value="'+s.service_id+'"]');if(c){c.checked=true;clientForm.elements['assigned_fee['+s.service_id+']'].value=s.assigned_fee;}})}new bootstrap.Modal('#clientModal').show();});});
</script>
<?php include __DIR__ . '/includes/footer.php'; include __DIR__ . '/includes/scripts.php'; ?>
