<?php
require_once __DIR__ . '/auth/auth_check.php';
require_once __DIR__ . '/config/billing_helpers.php';
$pageTitle='Generate Bill'; $active='generate_bill'; $clients=$pdo->query("SELECT id,name,trade_name FROM clients WHERE status=1 ORDER BY name")->fetchAll();
include __DIR__.'/includes/head.php'; include __DIR__.'/includes/sidebar.php'; include __DIR__.'/includes/topbar.php';
?>
<div class="page-title"><div><h1>Generate Bill</h1><p class="muted">Create bill from assigned services or custom work.</p></div></div>
<form class="panel-card" id="billForm" action="ajax/bill-save.php" method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">Client</label><select class="form-select" name="client_id" id="clientSelect" required><option value="">Select Client</option><?php foreach($clients as $c): ?><option value="<?= (int)$c['id'] ?>"><?= e($c['name'].' - '.$c['trade_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Bill Date</label><input class="form-control" type="date" name="bill_date" value="<?= date('Y-m-d') ?>"></div></div><hr><div id="items"></div><button class="btn btn-outline-primary my-2" type="button" id="addCustom">Add Custom Item</button><div class="row g-3 mt-2"><div class="col-md-3"><label class="form-label">Discount</label><input class="form-control calc" name="discount" id="discount" type="number" step="0.01" value="0"></div><div class="col-md-3"><label class="form-label">Tax Amount</label><input class="form-control calc" name="tax_amount" id="tax_amount" type="number" step="0.01" value="0"></div><div class="col-md-3"><label class="form-label">Grand Total</label><input class="form-control" id="grand" readonly></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"></textarea></div></div><button class="btn btn-primary mt-3" type="submit">Generate Bill</button></form>
<script>
function row(id,name,rate,desc=''){return `<div class="row g-2 bill-row mb-2"><input type="hidden" name="service_id[]" value="${id||0}"><div class="col-md-3"><input class="form-control" name="service_name[]" value="${name||''}" placeholder="Service / Work" required></div><div class="col-md-4"><input class="form-control" name="description[]" value="${desc}" placeholder="Description"></div><div class="col-md-1"><input class="form-control calc qty" name="qty[]" type="number" step="0.01" value="1"></div><div class="col-md-2"><input class="form-control calc rate" name="rate[]" type="number" step="0.01" value="${rate||0}"></div><div class="col-md-2"><input class="form-control amount" readonly></div></div>`}
function calc(){let sub=0;document.querySelectorAll('.bill-row').forEach(r=>{const q=parseFloat(r.querySelector('.qty').value)||0,rate=parseFloat(r.querySelector('.rate').value)||0,amt=q*rate;r.querySelector('.amount').value=amt.toFixed(2);sub+=amt});grand.value=(sub-(parseFloat(discount.value)||0)+(parseFloat(tax_amount.value)||0)).toFixed(2)}
document.addEventListener('input',e=>{if(e.target.classList.contains('calc'))calc()});addCustom.onclick=()=>{items.insertAdjacentHTML('beforeend',row(0,'',0));calc()};clientSelect.onchange=async()=>{items.innerHTML='';const fd=new FormData();fd.append('client_id',clientSelect.value);const d=await safeFetch('ajax/get-client-services.php',{method:'POST',body:fd});if(d.success)d.services.forEach(s=>items.insertAdjacentHTML('beforeend',row(s.service_id,s.service_name,s.assigned_fee)));calc()};billForm.onsubmit=async e=>{e.preventDefault();const d=await safeFetch(billForm.action,{method:'POST',body:new FormData(billForm),button:billForm.querySelector('button[type=submit]')});if(d.success)Swal.fire({icon:'success',title:d.message,showDenyButton:true,showCancelButton:true,confirmButtonText:'View Bill PDF',denyButtonText:'Receive Payment',cancelButtonText:'Back to Bills'}).then(r=>{if(r.isConfirmed)location='bill-pdf.php?token='+d.token;else if(r.isDenied)location='receive-payment.php?bill='+d.token;else location='bills.php'});};
</script>
<?php include __DIR__.'/includes/footer.php'; include __DIR__.'/includes/scripts.php'; ?>
