<?php
require_once __DIR__ . '/auth/auth_check.php';
require_once __DIR__ . '/config/billing_helpers.php';
require_once __DIR__ . '/lib/fpdf/fpdf.php';

$receipt = find_receipt_by_token($_GET['token'] ?? '');
if (!$receipt) exit('Invalid receipt.');
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,8,firm('firm_name','Tax Firm'),0,1);
$pdf->SetFont('Arial','',10);
$pdf->MultiCell(0,5,trim(firm('address').' '.firm('city').' '.firm('state').' '.firm('pincode')));
$pdf->Cell(0,6,'Mobile: '.firm('mobile').' Email: '.firm('email'),0,1);
$pdf->Cell(0,6,'GSTIN: '.firm('gstin').' PAN: '.firm('pan'),0,1);
$pdf->Ln(4);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,8,'Payment Receipt',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(95,6,'Receipt No: '.$receipt['receipt_no'],0,0);
$pdf->Cell(95,6,'Receipt Date: '.$receipt['payment_date'],0,1);
$pdf->Cell(95,6,'Client: '.$receipt['client_name'],0,0);
$pdf->Cell(95,6,'Trade: '.$receipt['trade_name'],0,1);
$pdf->Cell(95,6,'Mobile: '.$receipt['mobile'],0,0);
$pdf->Cell(95,6,'Bill No: '.$receipt['bill_no'],0,1);
$pdf->Ln(4);
$pdf->Cell(80,7,'Payment Amount',0,0); $pdf->Cell(60,7,money($receipt['amount']),0,1);
$pdf->Cell(80,7,'Payment Mode',0,0); $pdf->Cell(60,7,$receipt['payment_mode'],0,1);
$pdf->Cell(80,7,'Reference No',0,0); $pdf->Cell(60,7,$receipt['reference_no'],0,1);
$pdf->Cell(80,7,'Total Bill Amount',0,0); $pdf->Cell(60,7,money($receipt['grand_total']),0,1);
$pdf->Cell(80,7,'Total Paid',0,0); $pdf->Cell(60,7,money($receipt['paid_amount']),0,1);
$pdf->Cell(80,7,'Balance Due',0,0); $pdf->Cell(60,7,money($receipt['due_amount']),0,1);
$pdf->Ln(3);
$pdf->MultiCell(0,5,'Amount in words: '.amount_in_words_indian($receipt['amount']));
$pdf->Cell(0,7,'Received By: '.$receipt['received_by_name'],0,1);
$pdf->Ln(12);
$pdf->Cell(120,6,firm('footer_text','Thank you.'),0,0);
$pdf->Cell(60,6,'Authorized Signature',0,1);
$pdf->Output('I', $receipt['receipt_no'].'.pdf');
