<?php
require_once __DIR__ . '/auth/auth_check.php'; require_once __DIR__ . '/config/billing_helpers.php';
$bill = !empty($_GET['bill']) ? find_bill_by_token($_GET['bill']) : null;
$bills=$pdo->query("SELECT b.*, c.name client_name FROM bills b JOIN clients c ON c.id=b.client_id WHERE b.due_amount>0 ORDER BY b.id DESC")->fetchAll();
$pageTitle='Receive Payment'; $active='payments';
include __DIR__.'/includes/head.php'; include __DIR__.'/includes/sidebar.php'; include __DIR__.'/includes/topbar.php';
?>
<div class="page-title"><div><h1>Receive Payment</h1><p class="muted">Post payment against pending bill.</p></div></div>
<form class="panel-card" id="payForm" action="ajax/payment-save.php" method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">Bill</label><select class="form-select" name="bill_id" id="bill_id" required><?php foreach($bills as $b): ?><option value="<?= (int)$b['id'] ?>" data-due="<?= e($b['due_amount']) ?>" <?= $bill && $bill['id']==$b['id']?'selected':'' ?>><?= e($b['bill_no'].' - '.$b['client_name'].' Due '.money($b['due_amount'])) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Payment Date</label><input class="form-control" type="date" name="payment_date" value="<?= date('Y-m-d') ?>"></div><div class="col-md-3"><label class="form-label">Amount</label><input class="form-control" type="number" step="0.01" name="amount" id="amount" required></div><div class="col-md-3"><label class="form-label">Mode</label><select class="form-select" name="payment_mode"><?php foreach(['Cash','UPI','Bank Transfer','Cheque','Card','Other'] as $m): ?><option><?= e($m) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Reference No</label><input class="form-control" name="reference_no"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"></textarea></div></div><button class="btn btn-primary mt-3">Save Payment</button></form>
<script>
function due(){return parseFloat(bill_id.selectedOptions[0]?.dataset.due||0)} amount.max=due(); bill_id.onchange=()=>amount.max=due(); payForm.onsubmit=async e=>{e.preventDefault();if(parseFloat(amount.value)>due()){Swal.fire('Error','Payment amount cannot exceed due amount.','error');return}const d=await safeFetch(payForm.action,{method:'POST',body:new FormData(payForm),button:payForm.querySelector('button')});if(d.success)Swal.fire({icon:'success',title:d.message,showCancelButton:true,confirmButtonText:'Download Receipt PDF',cancelButtonText:'Back to Bills'}).then(r=>{location=r.isConfirmed?'receipt-pdf.php?token='+d.token:'bills.php'});}
</script>
<?php include __DIR__.'/includes/footer.php'; include __DIR__.'/includes/scripts.php'; ?>
