<?php
require_once __DIR__ . '/auth/auth_check.php';
require_once __DIR__ . '/config/billing_helpers.php';
$pageTitle = 'Services'; $active = 'services';
$services = $pdo->query("SELECT * FROM services ORDER BY id DESC")->fetchAll();
include __DIR__ . '/includes/head.php'; include __DIR__ . '/includes/sidebar.php'; include __DIR__ . '/includes/topbar.php';
?>
<div class="page-title"><div><h1>Services</h1><p class="muted">Manage service catalog and fees.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#serviceModal" onclick="serviceForm.reset();service_id.value=''"><i class="bi bi-plus-lg me-2"></i>Add Service</button></div>
<div class="panel-card"><table class="table table-striped data-table nowrap w-100"><thead><tr><th>Name</th><th>Code</th><th>Category</th><th>Fee</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php foreach ($services as $s): ?><tr><td><?= e($s['service_name']) ?></td><td><?= e($s['service_code']) ?></td><td><?= e($s['service_category']) ?></td><td><?= money($s['default_fee']) ?></td><td><span class="badge text-bg-<?= $s['status'] ? 'success' : 'secondary' ?>"><?= $s['status'] ? 'Active' : 'Inactive' ?></span></td><td><button class="btn btn-sm btn-outline-primary edit-service" data-row='<?= e(json_encode($s)) ?>'><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger delete-service" data-id="<?= (int)$s['id'] ?>"><i class="bi bi-trash"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div>
<div class="modal fade" id="serviceModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content ajax-reload" id="serviceForm" action="ajax/service-save.php" method="post"><div class="modal-header"><h5 class="modal-title">Service</h5><button class="btn-close" data-bs-dismiss="modal" type="button"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" id="service_id"><div class="row g-3"><div class="col-md-6"><label class="form-label">Service Name</label><input class="form-control" name="service_name" required></div><div class="col-md-3"><label class="form-label">Code</label><input class="form-control" name="service_code"></div><div class="col-md-3"><label class="form-label">Category</label><input class="form-control" name="service_category"></div><div class="col-md-4"><label class="form-label">Default Fee</label><input class="form-control" type="number" step="0.01" name="default_fee" required></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary" type="submit">Save</button></div></form></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{bindAjaxForm('.ajax-reload');document.querySelectorAll('.edit-service').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.row);service_id.value=d.id;for(const k in d){const el=serviceForm.elements[k];if(el)el.value=d[k]??'';}new bootstrap.Modal('#serviceModal').show();});document.querySelectorAll('.delete-service').forEach(b=>b.onclick=()=>Swal.fire({title:'Mark inactive?',showCancelButton:true}).then(async r=>{if(r.isConfirmed){const fd=new FormData();fd.append('csrf_token','<?= e(csrf_token()) ?>');fd.append('id',b.dataset.id);const data=await safeFetch('ajax/service-delete.php',{method:'POST',body:fd});if(data.success)location.reload();}}));});
</script>
<?php include __DIR__ . '/includes/footer.php'; include __DIR__ . '/includes/scripts.php'; ?>
